display_name: Fluxora

icon: ./assets/images/icon.png

keywords:
  - Fluxora
  - Fluxora
  - Clash
  - ClashMeta
  - Proxy

generic_name: Fluxora

categories:
  - Network

startup_notify: true
startup_wm_class: io.fluxora.app

include: []