script_template: inno_setup.iss
app_id: 5F0E8A64-3D57-4F11-9B20-6A8D4C7E1F32
app_name: Fluxora
publisher: Fluxora
publisher_url: https://github.com/Tiam9173/fluxora
display_name: Fluxora
executable_name: Fluxora.exe
output_base_file_name: Fluxora.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin
